### PR TITLE
Fix: Add maximum points validation and business rules

### LINKED ISSUE #85: Fix Points Validation Bug
**Description:**
While the Points class validates non-negative values in constructors, there's no validation for reasonable upper bounds or business logic constraints.

### PR DESCRIPTION
**Pull request by javierchuaby**
### Enhance points validation with reasonable upper bounds
Adds comprehensive validation to Points class to prevent unrealistic values and improve system robustness.

**Changes:**
- Define reasonable maximum points limit (1,000,000)
- Update Points constructor with upper bound validation
- Add comprehensive error messaging for validation failures
- Include business rule validation helper method

**Impact:** Prevents unrealistic point values, improves data integrity, and enhances system robustness against edge cases

Resolves #85

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Points.java [hunk 1]
```diff
@@ -62,17 +59,17 @@ public Points subtract(int delta) {
...
+        return value;
     }
 
     /**
-     * Returns the point value.
+     * Returns true if points value is within acceptable business rules
      */
-    public int getValue() {
-        return value;
+    public static boolean isValidPointsValue(int value) {
```
Comment (seanowww) [inline src/main/java/seedu/address/model/person/Points.java]: I liek that you adhered to coding standards

Comment (javierchuaby) [reply src/main/java/seedu/address/model/person/Points.java]: Thank you Sean! Do be more mindful of your spelling!
